### ISSUE TITLE
No fallback font on srt subtitle ? 

### ISSUE THREAD

**Issue by ghost** [macgo-player/bluray-player#11] opened 2018-12-19 16:38 UTC
App version 3.3.X - 3.3.9
macOS Mojave 10.14.2
UTF-8  srt subtitle

In the Simplified Chinese environment, I found that the font file used is `PingFang.ttc`.
PingFang.ttc Contains 3 fonts `PingFang TC`(Taiwan)  `PingFang HK`(HongKong)  `PingFang SC`(China). 
I found that it actually used `PingFang TC` ,Which is a Traditional Chinese font and no fallback font is set.
It can't show many glyph in Simplified Chinese , such as `U+6740  杀`  `U+654C  敌`.

Please Allows the user to specify the font of the srt subtitle or add a fallback font.

**Comment by macgo-dev** [comment] 2018-12-20 13:36
Could you please upload a sample srt file here?
Instructions: https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/

**Comment by ghost** [comment] 2018-12-20 13:51
FYI [sample.srt.zip](https://github.com/macgo-player/bluray-player/files/2699093/sample.srt.zip)

**Comment by macgo-dev** [comment] 2018-12-20 14:43
Thank you very much. I can reproduce this issue with your sample file. `杀` and `敌` are rendered as square boxes.

I think I can find a way to fix this issue by rendering characters correctly without user intervention, at least in most cases.

**Comment by macgo-dev** [comment] 2019-01-17 20:02
This issue is caused by lack of font index setup. The font index is hard-coded to 0.

https://github.com/videolan/vlc-3.0/blob/a7505eeb251398575ca34944a1215ea2b84b17ac/modules/text_renderer/freetype/fonts/darwin.c#L113

libass has a good implementation for such a situation.

**Comment by macgo-dev** [comment] 2019-01-21 19:07
I've added a patch to this issue and it will be included in the next update.

**Comment by macgo-dev** [comment] 2019-02-12 13:42
This issue should be fixed now in 3.3.10.

**Closed as completed by macgo-dev** 2019-02-12 13:42 UTC
