### ISSUE TITLE
Blu-ray Player Pro v3.3.10 crashes at initial disc read

### ISSUE THREAD

**Issue by fhgwright** [macgo-player/bluray-player#16] opened 2019-02-10 19:10 UTC
In attempting to play the "Lost City of Z" Blu-ray (with v3.3.9), I was presented with an update offer for v3.3.10 (while it was starting to play the disc).  I accepted it, but after it had installed the update and restarted, it crashed.  After some investigation, I found:

1.  It crashes on startup if a disc is present.

1.  It doesn't crash on startup if no disc is present.

1.  Loading a disc after it launches causes it to crash.

1.  Deleting the preference file (com.macblurayplayer.MacBlurayPlayer3-Pro.plist) doesn't help.

1.  Reinstalling the program from the (now manually fetched) .dmg fixes it **once**.

1.  Exiting and restarting the program after the reinstall (with a disc present) crashes again.

1.   Reinstalling it again fixes it again, but again only for one run.

This is with OSX 10.9.5 on a mid-2012 Mac Pro.

Rolling back to 3.3.9 fixes the problem.

I've attached the most recent of the 10 crash logs that I got during this process.  I needed to append a ".txt" extension to make the GitHub attachment uploader happy.

[Blu-ray Player_2019-02-10-101935_MacPro.crash.txt](https://github.com/macgo-player/bluray-player/files/2849252/Blu-ray.Player_2019-02-10-101935_MacPro.crash.txt)

**Comment by macgo-dev** [comment] 2019-02-12 13:26
After reviewing the changes in 3.3.10 and the crash log, I found the crash is caused by a bug that accidentally invokes CFRelease twice.

I'll release an update in a few days.

**Comment by Bi11** [comment] 2019-02-27 10:27
This issue is fixed in 3.3.11.

**Closed as completed by Bi11** 2019-02-27 10:27 UTC

**Comment by fhgwright** [comment] 2019-02-27 21:17
Fix verified.
